INSERT INTO `#dbprefix#options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES
(3, 'update_options_now', '1', 'yes'),
(4, 'allowfb', '1', 'yes'),
(5, 'Fb_Key', '', 'yes'),
(6, 'Fb_Secret', '', 'yes'),
(7, 'allowtw', '0', 'yes'),
(10, 'allowg', '1', 'yes'),
(11, 'GClientID', '', 'yes'),
(12, 'GClientSecret', '', 'yes'),
(13, 'allowlocalreg', '1', 'yes'),
(14, 'recaptcha-sk', '', 'yes'),
(15, 'recaptcha-se', '', 'yes'),
(19, 'site-logo-text', 'Site title', 'yes'),
(20, 'theme', 'main', 'yes'),
(21, 'recap-secret', '', 'yes'),
(22, 'bpp', '28', 'yes'),
(23, 'thumb-width', '205', 'yes'),
(24, 'thumb-height', '114', 'yes'),
(25, 'RelatedSource', '1', 'yes'),
(26, 'video-coms', '0', 'yes'),
(27, 'site-copyright', '© 2016 Edit me', 'yes'),
(28, 'licto', 'Edit me too!', 'yes'),
(29, 'googleanalitycs', '', 'yes'),
(30, 'hide-mp4', '0', 'yes'),
(31, 'choosen-player', '1', 'yes'),
(32, 'remote-player', '1', 'yes'),
(33, 'youtube-player', '0', 'yes'),
(34, 'video-width', '1280', 'yes'),
(35, 'video-height', '860', 'yes'),
(36, 'related-nr', '24', 'yes'),
(37, 'jwkey', 'gWUocJ//T//iYLr843MXTLwOfu2dM158DD/nLg==', 'yes'),
(38, 'musicthumb', 'http://37.media.tumblr.com/c87921eefd315482e66706d51a05054e/tumblr_n71ifjJAwU1tchrkco1_500.gif', 'yes'),
(39, 'SiteBasePath', '', 'yes'),
(40, 'video-seo-url', '/video/:id/:name', 'yes'),
(41, 'profile-seo-url', '/profile/:name/:id/:section', 'yes'),
(42, 'article-seo-url', '/article/:name/:id', 'yes'),
(43, 'page-seo-url', '/read/:name/:id', 'yes'),
(44, 'channel-seo-url', '/channel/:name/:id/:section', 'yes'),
(45, 'uploadrule', '1', 'yes'),
(46, 'sharingrule', '1', 'yes'),
(47, 'mp3rule', '1', 'yes'),
(48, 'musicembed', '1', 'yes'),
(49, 'imgrule', '1', 'yes'),
(50, 'alext', 'flv,mp4,avi,mpeg', 'yes'),
(51, 'alimgext', 'png,gif,jpg,jpeg', 'yes'),
(52, 'ffmpeg-thumb-time', '00:00:03', 'yes'),
(53, 'maxup', '3145728000', 'yes'),
(54, 'mediafolder', 'media', 'yes'),
(55, 'videos-initial', '1', 'yes'),
(56, 'editrule', '1', 'yes'),
(57, 'site-logo', '', 'yes'),
(58, 'binpath', '/usr/bin/php', 'yes'),
(59, 'ffa', '1', 'yes'),
(60, 'ffmpeg-vsize', '640x360', 'yes'),
(61, 'ffmpeg-cmd', 'ffmpeg', 'yes'),
(62, 'fftheme', '{ffmpeg-cmd} -i {input} -vcodec libx264 -s {ffmpeg-vsize} -threads 4 -movflags faststart {output}.mp4', 'yes'),
(63, 'tmp-folder', 'rawmedia', 'yes'),
(64, 'player-logo', '', 'yes'),
(65, 'upmenu', '1', 'yes'),
(66, 'musicmenu', '1', 'yes'),
(67, 'imagesmenu', '1', 'yes'),
(68, 'showplaylists', '1', 'yes'),
(69, 'showusers', '1', 'yes'),
(70, 'offline', '0', 'yes'),
(71, 'googletracking', '', 'yes'),
(72, 'youtubekey', '', 'yes'),
(73, 'tags', '360', 'yes'),
(74, 'fftheme-240', '{ffmpeg-cmd} -i {input}  -s 426x240 -c:v libx264 -preset veryfast -crf 28 -threads 2 -movflags faststart {output}-240.mp4 2>&1', 'yes'),
(75, 'fftheme-360', '{ffmpeg-cmd} -i {input} -s 640x360 -c:v libx264 -preset slow -crf 28 -threads 2 -movflags faststart {output}-360.mp4 2>&1', 'yes'),
(76, 'fftheme-480', '{ffmpeg-cmd} -i {input} -s 854x480 -c:v libx264 -preset veryfast -crf 28 -threads 2 -movflags faststart {output}-480.mp4 2>&1', 'yes'),
(77, 'fftheme-720', '{ffmpeg-cmd} -i {input} -vf scale=-1:720 -c:v libx264 -preset veryfast -crf 28 -threads 2 -movflags faststart {output}-720.mp4 2>&1', 'yes'),
(78, 'fftheme-1080', '{ffmpeg-cmd} -i {input} -vf scale=-1:1080 -c:v libx264 -preset veryfast -crf 28 -threads 2 -movflags faststart {output}-1080.mp4 2>&1', 'yes'),
(79, 'fftheme-1440', '{ffmpeg-cmd} -i {input} -vf scale=-1:1440 -c:v libx264 -preset veryfast -crf 28 -threads 2 -movflags faststart {output}-1440.mp4 2>&1', 'yes'),
(80, 'fftheme-2160', '{ffmpeg-cmd} -i {input} -vf scale=-1:2160 -c:v libx264 -preset veryfast -crf 28 -threads 2 -movflags faststart {output}-2160.mp4 2>&1', 'yes'),
(81, 'ffmeg-qualities', '360', 'yes'),
(82, 'def_lang', 'en', 'yes');


INSERT INTO `#dbprefix#langs` (`lang_id`, `term`) VALUES
(1, 'Show sidebar'),
(2, 'Upload a file'),
(3, 'Share media by '),
(4, 'Notifications'),
(5, 'My profile'),
(6, 'Profile Management'),
(7, 'Change password'),
(8, 'Logout'),
(9, 'Search videos'),
(10, 'Browse'),
(11, 'Most Viewed'),
(12, 'Featured'),
(13, 'Most Liked'),
(14, 'My stuff'),
(15, 'Create playlist'),
(16, 'Manage playlists'),
(17, 'Manage likes'),
(18, 'Manage videos'),
(19, 'Back one level'),
(20, 'Subions'),
(21, 'My playlists'),
(22, 'Play all'),
(23, 'by'),
(24, 'views'),
(25, 'Facebook fans'),
(26, 'Top playlists'),
(27, 'Newest users'),
(28, '404'),
(29, 'oops! page not found'),
(30, 'Back to home'),
(290, 'Featured Description'),
(289, 'Waiting for upload'),
(288, 'Video details'),
(287, 'Share a video'),
(286, 'share'),
(285, 'Disliked a video'),
(284, 'liked a video'),
(283, 'in playlist '),
(282, 'collected a video'),
(281, 'on video'),
(280, 'commented'),
(279, 'shared a video'),
(278, 'Login first!'),
(277, 'Most Viewed Description'),
(275, 'watched a video'),
(276, 'Browse Description'),
(274, 'Error. Please go back'),
(273, 'Most Liked Description'),
(272, 'Sorry but there are no results.'),
(271, 'This URL is invalid or the video is removed by the provider.'),
(270, 'Unknown provider or incorrect URL. Please try again.'),
(269, 'Popular channels'),
(268, 'Buzz'),
(267, 'Subscribed to'),
(266, 'Subscribers'),
(263, 'Name'),
(264, 'About'),
(265, 'Reported by'),
(262, 'Avatar'),
(261, 'Subscriptions'),
(260, 'Share media by link'),
(259, 'Owner'),
(258, 'Playlist'),
(257, 'Create channel'),
(256, 'Channel image'),
(255, 'Description'),
(254, 'Choose a parentcategory:'),
(253, 'Child of:'),
(252, 'Your channel''s title'),
(251, 'Title'),
(248, 'Channel'),
(249, 'Delete selected'),
(250, 'Delete'),
(247, 'Details & embed'),
(246, 'Please login in order to collect videos.'),
(245, 'Please login in order to report videos.'),
(244, 'Report video'),
(243, 'Add To'),
(242, 'Dislike'),
(241, 'Like'),
(240, 'Subscribe'),
(239, 'Classic registration'),
(238, 'Google'),
(237, 'Google login'),
(236, 'Twitter'),
(235, 'Twitter login'),
(234, 'Facebook'),
(233, 'Facebook login'),
(232, 'Login'),
(231, 'Loading the player...'),
(230, 'Add video'),
(229, 'Safe'),
(228, 'Not safe'),
(225, 'Description:'),
(226, 'Tags:'),
(227, 'NSFW:'),
(224, 'Choose a category:'),
(223, 'Category:'),
(222, 'In seconds'),
(221, 'Duration:'),
(220, 'Link to web image file.'),
(217, 'Title:'),
(218, 'Thumbnail:'),
(219, 'http://www.dailymotion.com/img/x116zuj_imbroglio_shortfilms.jpg'),
(216, 'New video details'),
(214, 'Continue'),
(215, 'Share video by iframe/embed'),
(213, 'Remote file (direct link to .mp4,.flv file)'),
(211, 'OR'),
(212, 'http://www.mycustomhost.com/video/rihanna-file.mp4'),
(210, 'Link to video (Youtube, Metacafe, etc)'),
(208, 'Social video link:'),
(209, 'http://www.dailymotion.com/video/x116zuj_imbroglio_shortfilms'),
(207, 'New video'),
(206, 'Unfeature video'),
(205, 'Publish video'),
(204, 'Permanently delete video'),
(203, 'Publish selected'),
(202, 'View'),
(201, 'Feature video'),
(200, 'Edit'),
(199, 'Unpublish'),
(198, 'Unpublish selected'),
(197, 'Likes'),
(196, 'Duration'),
(195, 'Video'),
(194, 'Thumb'),
(193, 'Last'),
(192, 'First'),
(191, 'Update settings'),
(190, 'Reports'),
(189, 'Comments'),
(188, 'Playlists'),
(187, 'Video likes'),
(186, 'Video views'),
(185, 'Members'),
(184, 'Videos'),
(183, 'Username & password'),
(291, 'ilike'),
(292, 'Reason for reporting'),
(293, 'Video not playing'),
(294, 'Wrong title/description'),
(295, 'Video is offensive'),
(296, 'Video is restricted'),
(297, 'Copyrighted material'),
(298, 'Details of the report'),
(299, 'Send report'),
(300, 'You have no playlists that don''t contain this video'),
(301, 'enterComment'),
(302, 'comment'),
(303, 'Share video by link'),
(304, 'Sign in to Your Account'),
(305, 'Email'),
(306, 'Email address'),
(307, 'Password'),
(308, 'forgot your password?'),
(309, 'Your Password'),
(310, 'Sign in'),
(311, 'Join with '),
(312, 'It''s you'),
(313, 'Interesting people'),
(314, 'created successfully.'),
(315, 'Manage videos.'),
(316, 'Upload avatar'),
(317, 'Unsubscribe'),
(318, 'Collect in selected'),
(319, 'registration'),
(320, 'Create a new Account'),
(321, 'Your stage name'),
(322, 'Choose Password'),
(323, 'Repeat Password'),
(324, 'City'),
(325, 'Country'),
(326, 'Register'),
(327, 'About you'),
(328, 'Gender'),
(329, 'Male'),
(330, 'Female'),
(331, 'Social profiles can be left blank, if added they become public.'),
(332, 'Facebook page'),
(333, 'my.fan.url'),
(334, 'Without'),
(335, 'Google Plus'),
(336, 'my.google.id'),
(337, 'my.twitter.id'),
(338, 'Save changes'),
(339, 'Control panel'),
(340, 'Avatar changed.'),
(341, 'liked a comment'),
(342, 'Subscription added!'),
(343, 'You'),
(344, 'this'),
(345, 'Link to original video image file. Don''t change this to use video default (if any in left)'),
(346, 'We don''t support yet embeds from that website'),
(347, 'Videos unpublished.'),
(348, 'Video unpublished.'),
(349, 'Your playlist''s title'),
(350, 'Playlist image'),
(351, 'You and XXX'),
(352, 'You like this'),
(353, 'Liked'),
(354, 'Remove selected'),
(355, 'Remove rating'),
(356, 'Image'),
(357, 'Select only if you wish to change the image'),
(358, 'Duration (in seconds):'),
(359, 'No change'),
(360, 'Initial category is'),
(361, 'Update video'),
(362, 'Wrong username or password.'),
(363, 'Unknown provider or incorrect URL. Please try again.'),
(379, 'Facebook login'),
(380, 'Classic registration'),
(381, 'Unknown provider or incorrect URL. Please try again.'),
(382, 'Twitter login'),
(383, 'Back one level'),
(384, 'Login'),
(385, 'Back one level'),
(386, 'Video likes'),
(387, 'Twitter login'),
(388, 'Most Liked'),
(389, 'oops! page not found'),
(390, 'Back one level'),
(391, 'Sign in'),
(392, 'Join with '),
(393, 'Twitter'),
(394, 'Most Viewed'),
(395, 'Password'),
(396, 'Facebook login'),
(397, 'Featured'),
(398, 'Your Password'),
(399, 'Show sidebar'),
(400, 'Videos'),
(401, 'Most Liked'),
(402, 'This URL is invalid or the video is removed by the provider.'),
(403, 'Browse'),
(404, 'Browse'),
(405, 'Show sidebar'),
(406, 'Videos'),
(407, 'Unknown provider or incorrect URL. Please try again.'),
(408, 'Classic registration'),
(409, 'Twitter login'),
(410, 'Google '),
(411, 'Show sidebar'),
(412, 'Facebook login'),
(413, 'Most Viewed'),
(414, 'Playlists'),
(415, 'Email address'),
(416, 'Most Viewed'),
(417, 'Login'),
(418, 'Password'),
(419, 'language-name'),
(420, 'Hide'),
(421, 'Link to video'),
(422, 'Embed code'),
(423, 'Import selected'),
(424, 'Recover password'),
(425, 'Change language'),
(426, 'No homeblocks defined by administrator.'),
(427, ''),
(428, 'One like'),
(429, 'Update channel'),
(430, 'Visitor'),
(431, 'User & pass'),
(432, 'My Buzz'),
(433, 'New playlist'),
(434, 'My likes'),
(435, 'My videos'),
(436, 'You and XXX like this'),
(437, 'You and XXX other like this'),
(438, 'Write your comment'),
(439, 'You and XXX others like this'),
(440, 'Click to remove subscription'),
(441, 'Subscribed'),
(442, 'Click to add a subscription'),
(443, 'You already'),
(444, 'Playlist created.'),
(445, ' created.'),
(446, 'Delete playlist'),
(447, 'Already subscribed!'),
(448, 'Recover'),
(449, 'All done!'),
(450, 'No playlist selected'),
(451, 'Permanently delete videos'),
(452, 'You +1 like this'),
(453, 'Subscription removed!'),
(454, 'Email already in use'),
(455, 'Video editing has been disabled by the administrator'),
(456, 'Video edited.'),
(457, ' updated.'),
(458, 'Report not sent! Please make sure you complete all fields'),
(459, 'Something went wrong, please try again.'),
(460, 'Invalid Login system'),
(461, 'Something went wrong: Missing file or thumbnail'),
(462, 'Seems that link it''s not valid or link is wrong'),
(463, 'Password changed.'),
(464, 'is not registered to any account.'),
(465, 'Passwords do not match.'),
(466, 'Remove from playlist'),
(467, 'XXX like this'),
(468, 'commented on the video'),
(469, 'liked a comment on the video'),
(470, 'collected a video in playlist '),
(471, 'Activity'),
(472, 'Videos shared'),
(473, 'Liked videos'),
(474, 'All activity'),
(475, 'On this list'),
(476, 'Watched'),
(477, 'Watched videos'),
(478, 'change'),
(479, 'my.profile.username'),
(480, 'my.twitter.username'),
(481, 'Upload cover'),
(482, 'Cover upload failed.'),
(483, 'Change profile images'),
(484, 'Change profile data'),
(485, 'Avatar upload failed.'),
(486, 'Success!'),
(487, 'You are now subscribed!'),
(1086, 'Add image'),
(1087, 'Choose picture:'),
(1084, 'Embed this media on your page'),
(1085, 'Embed (Responsive)'),
(490, 'Hmm..have a name stranger?!'),
(491, 'Please login in order to like a video! It''s fast and worth it'),
(492, 'Ohhh!'),
(493, 'Edit your details'),
(494, 'Change avatar'),
(495, 'Change cover'),
(496, 'Change picture'),
(497, 'Change cover (1170px/315px)'),
(498, 'Like this comment'),
(499, 'SHARE:'),
(500, 'Embed this video'),
(501, 'You are already subscribed!'),
(502, 'uploaded successfully.'),
(503, 'This video will be available after conversion.'),
(504, 'Channels'),
(505, 'New users'),
(506, 'My subscriptions'),
(507, 'Language'),
(508, 'Upload video'),
(509, 'Search'),
(510, 'Upload a video from your PC'),
(511, 'Share a web video'),
(512, 'Upload an image from your PC'),
(513, 'Upload image from your PC'),
(514, 'What you''ve been up to?'),
(515, 'Post now'),
(516, ' Post now'),
(517, 'What''s you''ve been up to?'),
(518, 'What''s in this picture?'),
(519, 'Tell us a bit more maybe?'),
(520, 'The picture''s title'),
(521, 'What''s in this picture? Tell your friends a bit more maybe?'),
(522, 'Say something about this picture'),
(523, 'picture'),
(524, ' Continue'),
(525, 'http://www.youtube.com/watch?v=fIadOXV1wVg'),
(526, 'What''s this picture?'),
(527, 'Say something more about this picture'),
(528, 'Image category:'),
(529, 'Embed this video as 480x360'),
(530, 'Embed this video as 640x480'),
(531, 'Next video starting soon'),
(532, 'Information'),
(533, 'Choose a spot:'),
(534, 'In order to change your password please follow this link:'),
(535, 'Password change for'),
(536, 'An e-mail has been sent to your account. Please also check the "spam" folder.'),
(537, 'Report sent!'),
(538, 'Login first'),
(539, 'Add to playlist(s)'),
(540, 'Select channel:'),
(541, 'Sort'),
(542, 'This Week'),
(543, 'All'),
(544, 'This Month'),
(545, 'This Year'),
(546, 'This Years'),
(547, 'Last login:'),
(548, 'Registered:'),
(549, 'View all'),
(550, 'Filter results'),
(551, 'Filter videos'),
(552, 'Most Commented Description'),
(553, 'Most Commented'),
(554, 'New Videos'),
(555, 'Feed'),
(556, 'Passwords are not the same');

INSERT INTO `#dbprefix#languages` (`term_id`, `lang_name`, `lang_code`, `lang_terms`) VALUES
(31, 'English', 'en', '{"language-name":"English","Show sidebar":"Show sidebar","Upload a file":"Upload a file","Share media by ":"Share media by ","Notifications":"Notifications","My profile":"My profile","Profile Management":"Profile Management","Change password":"Change password","Logout":"Logout","Search videos":"Search videos","Browse":"Browse","Most Viewed":"Most Viewed","Featured":"Featured","Most Liked":"Most Liked","My stuff":"My stuff","Create playlist":"Create playlist","Manage playlists":"Manage playlists","Manage likes":"Manage likes","Manage videos":"Manage videos","Back one level":"Back one level","Subions":"Subions","My playlists":"My playlists","Play all":"Play all","by":"by","views":"views","Facebook fans":"Facebook fans","Top playlists":"Top playlists","Newest users":"Newest users","404":"404","oops! page not found":"oops! page not found","Back to home":"Back to home","Featured Description":"Featured Description","Waiting for upload":"Waiting for upload","Video details":"Video details","Share a video":"Share a video","share":"share","Disliked a video":"Disliked a video","liked a video":"liked a video","in playlist ":"in playlist ","collected a video":"collected a video","on video":"on video","commented":"commented","shared a video":"shared a video","Login first!":"Login first!","Most Viewed Description":"Most Viewed Description","watched a video":"watched a video","Browse Description":"Browse Description","Error. Please go back":"Error. Please go back","Most Liked Description":"Most Liked Description","Sorry but there are no results.":"Sorry but there are no results.","This URL is invalid or the video is removed by the provider.":"This URL is invalid or the video is removed by the provider.","Unknown provider or incorrect URL. Please try again.":"Unknown provider or incorrect URL. Please try again.","Popular channels":"Popular channels","Buzz":"Buzz","Subscribed to":"Subscribed to","Subscribers":"Subscribers","Name":"Name","About":"About","Reported by":"Reported by","Avatar":"Avatar","Subscriptions":"Subscriptions","Share media by link":"Share media by link","Owner":"Owner","Playlist":"Playlist","Create channel":"Create channel","Channel image":"Channel image","Description":"Description","Choose a parentcategory:":"Choose a parentcategory:","Child of:":"Child of:","Your channel''s title":"Your channel''s title","Title":"Title","Channel":"Channel","Delete selected":"Delete selected","Delete":"Delete","Details & embed":"Details & embed","Please login in order to collect videos.":"Please login in order to collect videos.","Please login in order to report videos.":"Please login in order to report videos.","Report video":"Report video","Add To":"Add To","Dislike":"Dislike","Like":"Like","Subscribe":"Subscribe","Classic registration":"Classic registration","Google":"Google","Google login":"Google login","Twitter":"Twitter","Twitter login":"Twitter login","Facebook":"Facebook","Facebook login":"Facebook login","Login":"Login","Loading the player...":"Loading the player...","Add video":"Add video","Safe":"Safe","Not safe":"Not safe","Description:":"Description:","Tags:":"Tags:","NSFW:":"NSFW:","Choose a category:":"Choose a category:","Category:":"Category:","In seconds":"In seconds","Duration:":"Duration:","Link to web image file.":"Link to web image file.","Title:":"Title:","Thumbnail:":"Thumbnail:","http:\\/\\/www.dailymotion.com\\/img\\/x116zuj_imbroglio_shortfilms.jpg":"http:\\/\\/www.dailymotion.com\\/img\\/x116zuj_imbroglio_shortfilms.jpg","New video details":"New video details","Continue":"Continue","Share video by iframe\\/embed":"Share video by iframe\\/embed","Remote file (direct link to .mp4,.flv file)":"Remote file (direct link to .mp4,.flv file)","OR":"OR","http:\\/\\/www.mycustomhost.com\\/video\\/rihanna-file.mp4":"http:\\/\\/www.mycustomhost.com\\/video\\/rihanna-file.mp4","Link to video (Youtube, Metacafe, etc)":"Link to video (Youtube, Metacafe, etc)","Social video link:":"Social video link:","http:\\/\\/www.dailymotion.com\\/video\\/x116zuj_imbroglio_shortfilms":"http:\\/\\/www.dailymotion.com\\/video\\/x116zuj_imbroglio_shortfilms","New video":"New video","Unfeature video":"Unfeature video","Publish video":"Publish video","Permanently delete video":"Permanently delete video","Publish selected":"Publish selected","View":"View","Feature video":"Feature video","Edit":"Edit","Unpublish":"Unpublish","Unpublish selected":"Unpublish selected","Likes":"Likes","Duration":"Duration","Video":"Video","Thumb":"Thumb","Last":"Last","First":"First","Update settings":"Update settings","Reports":"Reports","Comments":"Comments","Playlists":"Playlists","Video likes":"Video likes","Video views":"Video views","Members":"Members","Videos":"Videos","Username & password":"Username & password","ilike":"ilike","Reason for reporting":"Reason for reporting","Video not playing":"Video not playing","Wrong title\\/description":"Wrong title\\/description","Video is offensive":"Video is offensive","Video is restricted":"Video is restricted","Copyrighted material":"Copyrighted material","Details of the report":"Details of the report","Send report":"Send report","You have no playlists that don''t contain this video":"You have no playlists that don''t contain this video","enterComment":"enterComment","comment":"comment","Share video by link":"Share video by link","Sign in to Your Account":"Sign in to Your Account","Email":"Email","Email address":"Email address","Password":"Password","forgot your password?":"forgot your password?","Your Password":"Your Password","Sign in":"Sign in","Join with ":"Join with ","It''s you":"It''s you","Interesting people":"Interesting people","created successfully.":"created successfully.","Manage videos.":"Manage videos.","Upload avatar":"Upload avatar","Unsubscribe":"Unsubscribe","Collect in selected":"Collect in selected","registration":"registration","Create a new Account":"Create a new Account","Your stage name":"Your stage name","Choose Password":"Choose Password","Repeat Password":"Repeat Password","City":"City","Country":"Country","Register":"Register","About you":"About you","Gender":"Gender","Male":"Male","Female":"Female","Social profiles can be left blank, if added they become public.":"Social profiles can be left blank, if added they become public.","Facebook page":"Facebook page","my.fan.url":"my.fan.url","Without":"Without","Google Plus":"Google Plus","my.google.id":"my.google.id","my.twitter.id":"my.twitter.id","Save changes":"Save changes","Control panel":"Control panel","Avatar changed.":"Avatar changed.","liked a comment":"liked a comment","Subscription added!":"Subscription added!","You":"You","this":"this","Link to original video image file. Don''t change this to use video default (if any in left)":"Link to original video image file. Don''t change this to use video default (if any in left)","We don''t support yet embeds from that website":"We don''t support yet embeds from that website","Videos unpublished.":"Videos unpublished.","Video unpublished.":"Video unpublished.","Your playlist''s title":"Your playlist''s title","Playlist image":"Playlist image","You and XXX":"You and XXX","You like this":"You like this","Liked":"Liked","Remove selected":"Remove selected","Remove rating":"Remove rating","Image":"Image","Select only if you wish to change the image":"Select only if you wish to change the image","Duration (in seconds):":"Duration (in seconds):","No change":"No change","Initial category is":"Initial category is","Update video":"Update video","Wrong username or password.":"Wrong username or password.","Hide":"Hide","Link to video":"Link to video","Embed code":"Embed code","Import selected":"Import selected","Recover password":"Recover password","Change language":"Change language","No homeblocks defined by administrator.":"No homeblocks defined by administrator.","405":"","One like":"One like","Update channel":"Update channel","Visitor":"Visitor","User & pass":"User & pass","My Buzz":"My Buzz","New playlist":"New playlist","My likes":"My likes","My videos":"My videos","You and XXX like this":"You and XXX like this","You and XXX other like this":"You and XXX other like this","Write your comment":"Write your comment","You and XXX others like this":"You and XXX others like this","Click to remove subscription":"Click to remove subscription","Subscribed":"Subscribed","Click to add a subscription":"Click to add a subscription","You already":"You already","Playlist created.":"Playlist created."," created.":" created.","Delete playlist":"Delete playlist","Already subscribed!":"Already subscribed!","Recover":"Recover","All done!":"All done!","No playlist selected":"No playlist selected","Permanently delete videos":"Permanently delete videos","You +1 like this":"You +1 like this","Subscription removed!":"Subscription removed!","Email already in use":"Email already in use","Video editing has been disabled by the administrator":"Video editing has been disabled by the administrator","Video edited.":"Video edited."," updated.":" updated.","Report not sent! Please make sure you complete all fields":"Report not sent! Please make sure you complete all fields","Something went wrong, please try again.":"Something went wrong, please try again.","Invalid Login system":"Invalid Login system","Something went wrong: Missing file or thumbnail":"Something went wrong: Missing file or thumbnail","Seems that link it''s not valid or link is wrong":"Seems that link it''s not valid or link is wrong","Password changed.":"Password changed.","is not registered to any account.":"is not registered to any account.","Passwords do not match.":"Passwords do not match.","Remove from playlist":"Remove from playlist","XXX like this":"XXX like this","commented on the video":"commented on the video","liked a comment on the video":"liked a comment on the video","collected a video in playlist ":"collected a video in playlist ","Activity":"Activity","Videos shared":"Videos shared","Liked videos":"Liked videos","All activity":"All activity","On this list":"On this list","Watched":"Watched","Watched videos":"Watched videos","change":"change","my.profile.username":"my.profile.username","my.twitter.username":"my.twitter.username","Upload cover":"Upload cover","Cover upload failed.":"Cover upload failed.","Change profile images":"Change profile images","Change profile data":"Change profile data","Avatar upload failed.":"Avatar upload failed.","Success!":"Success!","You are now subscribed!":"You are now subscribed!","Hmm..have a name stranger?!":"Hmm..have a name stranger?!","Please login in order to like a video! It''s fast and worth it":"Please login in order to like a video! It''s fast and worth it","Ohhh!":"Ohhh!","Edit your details":"Edit your details","Change avatar":"Change avatar","Change cover":"Change cover","Change picture":"Change picture","Change cover (1170px\\/315px)":"Change cover (1170px\\/315px)","Like this comment":"Like this comment","SHARE:":"SHARE:","Embed this video":"Embed this video","You are already subscribed!":"You are already subscribed!","uploaded successfully.":"uploaded successfully.","This video will be available after conversion.":"This video will be available after conversion.","Channels":"Channels","New users":"New users","My subscriptions":"My subscriptions","Language":"Language","Upload video":"Upload video","Search":"Search","Upload a video from your PC":"Upload a video from your PC","Share a web video":"Share a web video","Upload an image from your PC":"Upload an image from your PC","Upload image from your PC":"Upload image from your PC","What you''ve been up to?":"What you''ve been up to?","Post now":"Post now"," Post now":" Post now","What''s you''ve been up to?":"What''s you''ve been up to?","What''s in this picture?":"What''s in this picture?","Tell us a bit more maybe?":"Tell us a bit more maybe?","The picture''s title":"The picture''s title","What''s in this picture? Tell your friends a bit more maybe?":"What''s in this picture? Tell your friends a bit more maybe?","Say something about this picture":"Say something about this picture","picture":"picture"," Continue":" Continue","http:\\/\\/www.youtube.com\\/watch?v=fIadOXV1wVg":"http:\\/\\/www.youtube.com\\/watch?v=fIadOXV1wVg","What''s this picture?":"What''s this picture?","Say something more about this picture":"Say something more about this picture","Image category:":"Image category:","Embed this video as 480x360":"Embed this video as 480x360","Embed this video as 640x480":"Embed this video as 640x480","Next video starting soon":"Next video starting soon","Information":"Information","Choose a spot:":"Choose a spot:","In order to change your password please follow this link:":"In order to change your password please follow this link:","Password change for":"Password change for","Report sent!":"Report sent!","Login first":"Login first","Add to playlist(s)":"Add to playlist(s)","Select channel:":"Select channel:","Sort":"Sort","This Week":"This Week","All":"All","This Month":"This Month","This Year":"This Year","This Years":"This Years","Last login:":"Last login:","Registered:":"Registered:","View all":"View all","Filter results":"Filter results","Filter videos":"Filter videos","Most Commented Description":"Most Commented Description","Most Commented":"Most Commented","New Videos":"New Videos","Feed":"Feed","Passwords are not the same":"Passwords are not the same","Upload":"Upload","Upload from PC":"Upload from PC","Web video":"Web video","Whats happening":"Whats happening","Profile":"Profile","Account":"Account","Forgot password":"Forgot password","Playlists deleted.":"Playlists deleted.","All Media Feed":"All Media Feed","Video Feed":"Video Feed","Music Feed":"Music Feed","Images Feed":"Images Feed","Report":"Report","Please login in order to report media.":"Please login in order to report media.","Video Channels":"Video Channels","Music Channels":"Music Channels","Image Categories":"Image Categories","New Media":"New Media","Recent":"Recent","Music":"Music","My Media":"My Media","Warning: No channels.":"Warning: No channels.","This video is not safe":"This video is not safe","I am under 18":"I am under 18","Missing video id":"Missing video id","No categories":"No categories","Choose owner:":"Choose owner:","Share a picture":"Share a picture","Choose an image:":"Choose an image:","Visibility":"Visibility","Users only":"Users only","Everybody":"Everybody","Manage media.":"Manage media.","www.dailymotion.com\\/video\\/x116zuj_imbroglio_shortfilms":"www.dailymotion.com\\/video\\/x116zuj_imbroglio_shortfilms","Channel:":"Channel:","Blog":"Blog","Share a melody":"Share a melody","Music category:":"Music category:","This video is not public!":"This video is not public!","Please login or register to watch it":"Please login or register to watch it","Something went wrong. Wrong credentials":"Something went wrong. Wrong credentials","Uploaded":"Uploaded","Embed video":"Embed video","Add to playlist":"Add to playlist","in the category":"in the category","Like this video":"Like this video","Recent Activity":"Recent Activity","Sort activity":"Sort activity","Uploads":"Uploads","disliked ":"disliked ","shared":"shared","Update playlist":"Update playlist","Followd by":"Followd by","Followed by":"Followed by","Following":"Following","liked a comment on":"liked a comment on","Top videos":"Top videos","Watch this video":"Watch this video","Browse Videos":"Browse Videos","The title":"The title","Create":"Create","Latest articles":"Latest articles","Blog categories":"Blog categories","Pages":"Pages","Articles":"Articles","Update":"Update","Read More":"Read More","added to ":"added to ","Skip this and Play":"Skip this and Play","Restart the video":"Restart the video","Large Player":"Large Player","Small Player":"Small Player","Stop playlist":"Stop playlist","Shortly offline":"Shortly offline","We''re working a bit on the website. Please get back shortly!":"We''re working a bit on the website. Please get back shortly!","Maintenance":"Maintenance","Should take a few minutes!":"Should take a few minutes!","Feature":"Feature","Song cover":"Song cover","Channels seo description":"Channels seo description","Group":"Group","Is admin":"Is admin","Id":"Id","k":"k","Vimeo category:":"Vimeo category:","All articles":"All articles","Account Settings":"Account Settings","See all video shared":"See all video shared","See all activity":"See all activity","Activities":"Activities","profile views":"profile views","Trending":"Trending","Post":"Post","Change cover <em>(height: 220px)<\\/em>":"Change cover <em>(height: 220px)<\\/em>","Report media":"Report media","Newest videos":"Newest videos","Recent Videos":"Recent Videos","Fresh videos":"Fresh videos","Selected by views":"Selected by views","Selected by user likes":"Selected by user likes","Discussed":"Discussed","Most commented on":"Most commented on","Watch Videos":"Watch Videos","Browse Channels":"Browse Channels","Video categories":"Video categories","Categories for music":"Categories for music","Categories with videos":"Categories with videos","Categories with music":"Categories with music","Pictures":"Pictures","Categories with images":"Categories with images","Images categories ":"Images categories ","Music categories ":"Music categories ","m":"m","Please login using the social service preferred or by using the e-mail and password from the previous registration.":"Please login using the social service preferred or by using the e-mail and password from the previous registration.","Signin with <strong>Facebook<\\/strong>":"Signin with <strong>Facebook<\\/strong>","Signin with <strong>Google<\\/strong>":"Signin with <strong>Google<\\/strong>","Signin with <strong>Twitter<\\/strong>":"Signin with <strong>Twitter<\\/strong>","If you don''t have an social account you can":"If you don''t have an social account you can","register here":"register here","Recover your password by e-mail. If you''ve used an social service, just click on the button for that service on the login page.":"Recover your password by e-mail. If you''ve used an social service, just click on the button for that service on the login page.","If you don''t have an account yet you can":"If you don''t have an account yet you can","Thank you for deciding to join the fun!.":"Thank you for deciding to join the fun!.","Complete the form in the right or choose a fast social registration and let''s get started!":"Complete the form in the right or choose a fast social registration and let''s get started!","Thank you for deciding to join the fun!":"Thank you for deciding to join the fun!","Select avatar":"Select avatar","Select your avatar":"Select your avatar","Create account":"Create account","Recent articles":"Recent articles","Newest images":"Newest images","Most Commented Songs Description":"Most Commented Songs Description","Newest Songs":"Newest Songs","Browse Songs Description":"Browse Songs Description","Most Viewed Songs Description":"Most Viewed Songs Description","Most Liked Songs Description":"Most Liked Songs Description","Filter Images":"Filter Images","Images":"Images","Filter activity":"Filter activity","Our Blog":"Our Blog","Sorry but there are no results":"Sorry but there are no results","https:\\/\\/www.youtube.com\\/watch?v=g5qU7p7yOY8":"https:\\/\\/www.youtube.com\\/watch?v=g5qU7p7yOY8","Video hosted on the web":"Video hosted on the web","Upload an mp3":"Upload an mp3","Upload a picture":"Upload a picture","Upload a video file":"Upload a video file","Embed a video from the web":"Embed a video from the web","You can embed from:":"You can embed from:","Embed":"Embed","Save & Create video":"Save & Create video","Create & Save video":"Create & Save video","Share a melody (mp3)":"Share a melody (mp3)","All time":"All time","All results in website":"All results in website","Only video published this week":"Only video published this week","Only from this week":"Only from this week","Only from this month":"Only from this month","Only uploaded this year":"Only uploaded this year","Last 7 days":"Last 7 days","This month only":"This month only","Current year":"Current year","All results":"All results","#":"#","Users":"Users","Hi , ":"Hi , ","Shared media":"Shared media","Settings":"Settings","Would you like to join our community and start sharing videos, following friends and collect media that interests you?":"Would you like to join our community and start sharing videos, following friends and collect media that interests you?","Would you like to join our community and share videos, follow friends and collect media that interests you?":"Would you like to join our community and share videos, follow friends and collect media that interests you?","View profile":"View profile","Activity on your videos":"Activity on your videos","Your latest fans":"Your latest fans","Dashboard":"Dashboard","Remove from liked":"Remove from liked","Remove!":"Remove!","You no longer like this.":"You no longer like this.","Video from followers":"Video from followers","From followers":"From followers","Remove":"Remove","Watch Later":"Watch Later","History":"History","Remove this":"Remove this","Videos by":"Videos by","Video manager":"Video manager","Channel manager":"Channel manager","Media shared by":"Media shared by","media files":"media files","entries.":"entries.","What you appreciate":"What you appreciate","Media liked by":"Media liked by","entries":"entries","liked by":"liked by","What you''ve watched":"What you''ve watched","watched by":"watched by","saved for later by":"saved for later by","Media manager":"Media manager","Playlists manager":"Playlists manager","playlists by":"playlists by","Create a new playlist":"Create a new playlist","Manage the videos in ":"Manage the videos in ","Share from SoundCloud":"Share from SoundCloud","Upload a melody (mp3)":"Upload a melody (mp3)","Link to SoundCloud user\\/track":"Link to SoundCloud user\\/track","Link to a SoundCloud user or track":"Link to a SoundCloud user or track","No results":"No results","Your details":"Your details","Browse Playlists":"Browse Playlists","Web hosted video":"Web hosted video","Browse our playlists":"Browse our playlists","Browse our members":"Browse our members","from":"from","Unknown":"Unknown","times":"times","Play all videos from":"Play all videos from","Play":"Play","Add to watch later":"Add to watch later","Error":"Error","You don''t seem to own this playlist.":"You don''t seem to own this playlist.","Already saved":"Already saved","This video was already in your watch list":"This video was already in your watch list","Added to watch later!":"Added to watch later!","Video is now in your watch later.":"Video is now in your watch later.","Video is now in your watch later list.":"Video is now in your watch later list.","Video was removed.":"Video was removed.","by choosing a social service you use on the right":"by choosing a social service you use on the right","by choosing a social service you use.":"by choosing a social service you use.","If you don''t have an account yet, you can":"If you don''t have an account yet, you can","Added":"Added","Featured video! Click to remove":"Featured video! Click to remove","Not featured. Click to feature video":"Not featured. Click to feature video","Unpublish all selected":"Unpublish all selected","Register First":"Register First","Reply":"Reply","Write your reply":"Write your reply","Added to playlist!":"Added to playlist!","Video is now in your playlist.":"Video is now in your playlist.","This video was already in your playlist":"This video was already in your playlist","Featured! Click to remove":"Featured! Click to remove","Not featured. Click to feature":"Not featured. Click to feature","This video is being processed":"This video is being processed","Please check back in a few minutes.":"Please check back in a few minutes.","Default subtitle":"Default subtitle","second":"second","minute":"minute","hour":"hour","day":"day","week":"week","month":"month","year":"year","decade":"decade","ago":"ago","lunis":"lunis","ores":"ores","saptamanis":"saptamanis","months":"months","hours":"hours","weeks":"weeks","lunas":"lunas","oras":"oras","saptamanas":"saptamanas","Guest":"Guest","minutes":"minutes","Login to comment.":"Login to comment.","Register or login to leave your impressions on this.":"Register or login to leave your impressions on this.","Login here to comment.":"Login here to comment.","Register or login to leave your impressions.":"Register or login to leave your impressions.","days":"days","seconds":"seconds","years":"years","from now":"from now","Friend''s Activity":"Friend''s Activity","Please login in order to collect a video! It''s fast and worth it":"Please login in order to collect a video! It''s fast and worth it","Link":"Link","Embed this video (responsive size)":"Embed this video (responsive size)","Filter songs":"Filter songs","Category to use:":"Category to use:","Import all selected":"Import all selected","My awesome slider":"My awesome slider","Featured Videos":"Featured Videos","Awesome message here":"Awesome message here","Hello, welcome!":"Hello, welcome!","Redtube category:":"Redtube category:","Choose a pornstar:":"Choose a pornstar:","Appreciation":"Appreciation","Users who liked this":"Users who liked this","Lives in":"Lives in","Hi, ":"Hi, ","Creator Studio":"Creator Studio","Home":"Home","My Channel":"My Channel","Beats":"Beats","Browse Categories":"Browse Categories","Watch liked videos":"Watch liked videos","Tell us what is wrong with the video is a fe words":"Tell us what is wrong with the video is a fe words","Tell us what is wrong with the video is a few words":"Tell us what is wrong with the video is a few words","Tell us what is wrong with the video in a few words":"Tell us what is wrong with the video in a few words","Media not playing":"Media not playing","Media is offensive":"Media is offensive","Media is restricted":"Media is restricted","Required : Tell us what is wrong with the video in a few words":"Required : Tell us what is wrong with the video in a few words","Required":"Required","Forgotten password":"Forgotten password","Recover by mail":"Recover by mail","Your e-mail":"Your e-mail","Recover now":"Recover now","Sing In":"Sing In","Still no account? Please go to":"Still no account? Please go to","Sing up":"Sing up","Close":"Close","Remember me":"Remember me","Forgot password?":"Forgot password?","Sign up":"Sign up","Create an account":"Create an account","Your name":"Your name","Channel name":"Channel name","Your e-mail must be valid.":"Your e-mail must be valid.","Passwords do not match":"Passwords do not match","Like this song":"Like this song","Listened":"Listened","Most Listened":"Most Listened","Filter":"Filter","New songs":"New songs","Listen later":"Listen later","No filter":"No filter","Featured Songs":"Featured Songs","Featured Songs Description":"Featured Songs Description","Most played songs":"Most played songs","Add song":"Add song","Songs we''ve picked for you":"Songs we''ve picked for you","Most hearted songs":"Most hearted songs","Most recently submited videos":"Most recently submited videos","Videos which have received the most views":"Videos which have received the most views","Videos which have received the most likes":"Videos which have received the most likes","Nothing here so far.":"Nothing here so far.","Share video":"Share video","Upload music":"Upload music","Upload pictures":"Upload pictures","Privacy":"Privacy","Followers only":"Followers only","Public":"Public","Add some tags":"Add some tags","HH":"HH","MM":"MM","SS":"SS","Videos which have received the most comments":"Videos which have received the most comments","See your subscribers":"See your subscribers","Videos we''ve picked for you":"Videos we''ve picked for you","Songs with most comments":"Songs with most comments","Longer than an hour?":"Longer than an hour?","Min":"Min","Sec":"Sec","Privacy:":"Privacy:","Or upload an mp3":"Or upload an mp3","Channel visits":"Channel visits","Shares":"Shares","Shares views":"Shares views","Media views":"Media views","more videos":"more videos","Songs":"Songs","more songs":"more songs","Send message":"Send message","Message":"Message","Collections":"Collections","Videos<\\/a>":"Videos<\\/a>","Images<\\/a>":"Images<\\/a>","Music<\\/a>":"Music<\\/a>","Activity<\\/a>":"Activity<\\/a>","Comments<\\/a>":"Comments<\\/a>","All followers":"All followers","All fans":"All fans","All subscriptions":"All subscriptions","Last Access:":"Last Access:","s":"s","Last online:":"Last online:","All videos by ":"All videos by ","All songs by ":"All songs by ","New images":"New images","New images shared":"New images shared","Featured images":"Featured images","Featured inages":"Featured inages","Images with most comments":"Images with most comments","Most liked images selection":"Most liked images selection","Most viewed images":"Most viewed images","Search media":"Search media","Chat with ":"Chat with ","Read at":"Read at","Your Studio":"Your Studio","Overview":"Overview","Channel settings":"Channel settings","Details":"Details","Social Links":"Social Links","Change details":"Change details","From city":"From city","From country":"From country","Channel about":"Channel about","Channel updated":"Channel updated","Open Facebook in new tab":"Open Facebook in new tab","Facebook profile link":"Facebook profile link","Google+ profile link":"Google+ profile link","Instagram profile link":"Instagram profile link","Open Google Plus in new tab":"Open Google Plus in new tab","Open Instagram in new tab":"Open Instagram in new tab","Twitter profile link":"Twitter profile link","Open Facebook":"Open Facebook","Open Google Plus":"Open Google Plus","Open Instagram":"Open Instagram","To Facebook":"To Facebook","To Google Plus":"To Google Plus","To Instagram":"To Instagram","To Google+":"To Google+","This will be visible on your profile":"This will be visible on your profile","To Twitter":"To Twitter","Optional. If added it will be visible on your profile":"Optional. If added it will be visible on your profile","Social profiles":"Social profiles","Choose picture":"Choose picture","Browse...":"Browse...","Current password":"Current password","New password":"New password","The old password is incorect.":"The old password is incorect.","Albums":"Albums","Latest activities":"Latest activities","Latest activity on your videos":"Latest activity on your videos","No activity yet":"No activity yet","Latest activity":"Latest activity","Embed image":"Embed image","Link to image":"Link to image","Embed this image as 480x360":"Embed this image as 480x360","Embed this image as 640x480":"Embed this image as 640x480","You have no playlists that don''t contain this image":"You have no playlists that don''t contain this image","Signin with <strong>Google Plus<\\/strong>":"Signin with <strong>Google Plus<\\/strong>","with":"with","Signin with":"Signin with","Login with":"Login with","Administration":"Administration","Login to upload":"Login to upload","googleplus":"googleplus","youtube":"youtube","pinterest":"pinterest","rss":"rss","skype":"skype","vimeo":"vimeo","dribbble":"dribbble","flickr":"flickr","linkedin":"linkedin","Feedburner":"Feedburner","Linked in":"Linked in"}');

